//
// Created by Алёна on 19.02.2023.
//

#ifndef NUMERICAL_METHODS_NSU_2_RELAXATION_METHOD_H
#define NUMERICAL_METHODS_NSU_2_RELAXATION_METHOD_H


class relaxation_method {

};


#endif //NUMERICAL_METHODS_NSU_2_RELAXATION_METHOD_H
